language: elixir
elixir: '1.10.3'
otp_release: '21.1'
services:
  - postgresql
  - docker
before_install:
  - echo "CREATE DATABASE plausible_test" > $HOME/init.sql
  - docker pull yandex/clickhouse-server
  - docker run -d -p 8123:8123 --ulimit nofile=262144:262144 --volume=$HOME/init.sql:/docker-entrypoint-initdb.d/init.sql yandex/clickhouse-server
  # setting up postgres 12 is quite a pain, see:
  # https://travis-ci.community/t/test-against-postgres-12/6768/8
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.4,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
env:
  - MIX_ENV=test PGVER=12
script: mix coveralls.travis
addons:
    postgresql: '12'
    apt:
      packages:
        - postgresql-12
        - postgresql-client-12
cache:
  directories:
    - _build
    - deps
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
