name: Build

on:
  push:
    branches: [master, stable, dev]
    tags: ['v*']
  pull_request:
    branches: [master]
    types: [opened, synchronize, labeled]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'preview'))
    runs-on: buildjet-4vcpu-ubuntu-2004

    steps:
      - name: Docker meta
        id: public-meta
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/metadata-action@v4
        with:
          images: plausible/analytics
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker meta
        id: private-meta
        if: startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/pulls/')
        uses: docker/metadata-action@v4
        with:
          images: plausible/analytics-private
          tags: |
            type=ref,event=pr
            type=ref,event=branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_METADATA=${{ steps.meta.outputs.json }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
