name: Elixir CI

on:
  pull_request:
  push:
    branches: [master, stable]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_VERSION: v7

jobs:
  full_build:
    name: Build and test
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: [15, 16]
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      clickhouse:
        image: clickhouse/clickhouse-server:23.3.7.5-alpine
        ports:
          - 8123:8123
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: marocchino/tool-versions-action@v1
        id: versions
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ steps.versions.outputs.elixir }}
          otp-version: ${{ steps.versions.outputs.erlang }}
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            priv/plts
            tracker/node_modules
            priv/tracker/js
          key: ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-${{ github.head_ref || github.ref }}-
            ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-refs/heads/master-
      - run: mix deps.get --only $MIX_ENV
      - run: npm install --prefix ./tracker
      - run: mix compile --warnings-as-errors --all-warnings
      - run: npm run deploy --prefix ./tracker
      - run: mix format --check-formatted
      - run: mix credo diff --from-git-merge-base origin/master
      - run: mix do ecto.create, ecto.migrate
      - run: mix test --include slow --include minio --max-failures 1 --warnings-as-errors
      - run: mix dialyzer

  small_build:
    name: Small build and small test
    env:
      MIX_ENV: small_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: [15, 16]
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      clickhouse:
        image: clickhouse/clickhouse-server:23.3.7.5-alpine
        ports:
          - 8123:8123
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: marocchino/tool-versions-action@v1
        id: versions
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ steps.versions.outputs.elixir }}
          otp-version: ${{ steps.versions.outputs.erlang }}
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            priv/plts
            tracker/node_modules
            priv/tracker/js
          key: ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-${{ github.head_ref || github.ref }}-
            ${{ env.MIX_ENV }}-${{ env.CACHE_VERSION }}-refs/heads/master-
      - run: mix deps.get --only $MIX_ENV
      - run: npm install --prefix ./tracker
      - run: mix compile --warnings-as-errors --all-warnings
      - run: npm run deploy --prefix ./tracker
      - run: mix do ecto.create, ecto.migrate
      - run: mix test --include slow --max-failures 1 --warnings-as-errors
